name: zffanalyze
adopt-info: zffanalyze
summary: Tool to analyze and verify zff files.
description: |
  zffanalyze is used analyze and verify zff files.
base: core24
grade: stable
confinement: strict
compression: lzo

platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  arm64:
    build-on: [arm64]
    build-for: [arm64]

parts:
  zffanalyze:
    build-packages: [ gcc, libacl1-dev ]
    plugin: rust
    rust-channel: "1.80.0"
    source: .
    override-pull: |
      craftctl default
      VERSION=$(grep -m1 '^version = ' Cargo.toml | sed -e 's/version = "\(.*\)"/\1/')
      [ -n "$(echo $VERSION)" ]
      if echo $VERSION | grep -q -E 'alpha|beta|rc'; then
        GRADE=devel
      else
        GRADE=stable
      fi
      craftctl set version="$VERSION"
      craftctl set grade="$GRADE"
      patch -d $SNAPCRAFT_PART_SRC/src/bin/res < $SNAPCRAFT_PROJECT_DIR/snap/local/constants_snap_hostfs_prefix.patch
apps:
  zffanalyze:
    command: bin/zffanalyze
    plugs:
      - home
      - system-backup