name: zffanalyze
adopt-info: zffanalyze
summary: Tool to analyze and verify zff files.
description: |
  zffanalyze is used analyze and verify zff files.
base: core22
grade: stable
confinement: strict
compression: lzo

architectures:
  - build-on: amd64
  - build-on: arm64

parts:
  # install rust manually
  rust-deps:
    plugin: nil
    build-packages:
      - curl
    override-pull: |
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  zffanalyze:
    after: [ rust-deps ]
    build-packages: [ gcc, libacl1-dev ]
    plugin: rust
    source: .
    override-pull: |
      snapcraftctl pull
      VERSION="$(git describe --tags --abbrev=0)"
      [ -n "$(echo $VERSION)" ] && GRADE=stable
      snapcraftctl set-version "$VERSION"
      snapcraftctl set-grade "$GRADE"
      patch -d $SNAPCRAFT_PART_SRC/src/bin/res < $SNAPCRAFT_PROJECT_DIR/snap/local/constants_snap_hostfs_prefix.patch
apps:
  zffanalyze:
    command: bin/zffanalyze
    plugs:
      - home
      - system-backup